# Google rustfmt configuration file.

edition = "2024"
style_edition = "2021"

# The "Default" setting has a heuristic which splits lines too aggresively.
# We are willing to revisit this setting in future versions of rustfmt.
# Bugs:
#   * https://github.com/rust-lang/rustfmt/issues/3119
#   * https://github.com/rust-lang/rustfmt/issues/3120
use_small_heuristics = "Max"

newline_style = "Unix"

# Note that this setting requires Rust Nightly
format_generated_files = false

wrap_comments = true
